eureka:
  client:
    register-with-eureka: true #表示是否注册进化uareka中
    fetch-registry: true #是否从Eureka抓取自己已有的注册信息，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
      #单机版
    service-url:
      defaultZone: http://localhost:7001/eureka
    #service-url:
      # 集群版
   #   defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: cloud-sellergoods-service-8001
    prefer-ip-address: true #访问路径可以显示IP地址